
spring:
  jpa:
    properties:
        hibernate:
          format_sql: true
          show_sql: true
    database: MYSQL
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: create
  datasource:
    url: jdbc:mysql://94.191.63.243:3306/jpa?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: harrison@onfresh.cn
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      use-global-data-source-stat: true
      filter:
        stat:
          log-slow-sql: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: localhost
    username: harrison
    password: 123456
    port: 5672
    virtual-host: harrison
server:
  port: 8080

database:
  url:jdbc:mysql:///jpa?autoReconnect=true&useSSL=false&characterEncoding=utf-8
  driverName:com.mysql.jdbc.Driver
  database.username:root
  database.password:123456
